### PR TITLE
Add login

### PR DESCRIPTION
**Pull request by klauszhang**
Basically add a login button on the toolbar so that user can login,
When click login will redirect to the login page
When login, if the user doesn't exist, a new user will be created.
When logout, the user will be logged out. It is not real, only use redux store to store user data. In real should be stored in localstorage, with a token or something.

When the same user login again, it will check its username / password. if wrong password, app will not let them in with a friendly message.

Created several graphql query and one mutation. 
```
#query
login(credential: UserCredentialInput!): User
isEmailRegistered(email: String!): EmailAvalibilityCheckResult

#mutations
createUser(credential: UserCredentialInput!): User
```
please refer to GraphiQL fro more info. or take a look at schema

In real, it should be the server's responsibilities to check email availability. But to demonstrate some work, I used server side checking approach. 

There's a test for action creator of login component. No other tests are written.
Server test seems broken.

Hope you like it.

Cheers.

### CODE REVIEW

**Comment by klauszhang** [comment]
sorry, it seems codeclimate doesn't like some parts of my code.
I believe I cannot make him happier... :(  LOL

**Comment by klauszhang** [comment]
I made a few commits to fix the stylelint issues. if you want we could revert this pr and put them in.
https://github.com/klauszhang/marvellous-browser/commit/331276492099f287db0f26a1f04345a17364ad2a
and 
for better code climate...
https://github.com/klauszhang/marvellous-browser/commit/a74c0a4886b4dbe80c534652ebba54b0e7cc54b7

**Comment by faceleg** [comment]
:)

I was just going to run eslint --fix to auto fix them.

But you should leave this now, we'll have a look at it today and I'll get JP to contact you :)

**Comment by faceleg** [comment]
Also with code climate, we use it as a tool to highlight *potential* issues - I usually glance through it, and I think the code is OK I approve it in code climate.

**Comment by klauszhang** [comment]
Thanks,
I tried `eslint --fix` it doesn't work... so I manually fixed them... I believe it is using stylelint and the latest version claim they support `--fix` but it does not do the work actually...
Cheers.

**Pull request merged**
